### ISSUE TITLE
Unable to run Jest with Create-React-App: "Not a test file"

### ISSUE THREAD

**Issue by shawnaxsom** [vim-test/vim-test#219]
Unless you unload your configuration, Create-React-App hides a lot of things in a React.js setup, including Jest. Under node_modules/react_scripts/package.json is where you will find Jest, not in your project root package.json. I was able to get Vim-Test working, but only after hacking the plugin, removing the package check from vim-test for Jest:

> autoload/test/javascript/jest.vim

>     function! test#javascript#jest#test_file(file) abort
>         return a:file =~# g:test#javascript#jest#file_pattern
>         " \ && test#javascript#has_package('jest')  " <--- It fails here
>     endfunction

I guess some options are to remove the check, add a flag to be able to remove the check, add an alternate variable for a different package.json to look at (probably the recommended path?), or make the check aware of Create-React-App (not agnostic enough I am sure).

Let me know your thoughts and if you would want a PR.

**Comment by codeinabox** [comment]
We plan address with #185 which lets you set the runner when the detection does not work

**Comment by janko-m** [comment]
I don't think it would be a good idea for vim-test to read `package.json` files from other dependencies, because then it would need to distinguish between `dependencies` and `devDependencies` (as in the latter case we shouldn't assume that `jest` is used in the main project as well, because it's just a development dependency of that package). This would mean we'd need to implement JSON parsing, or at least some smart parsing.

I agree with @codeinabox that https://github.com/janko-m/vim-test/issues/185 would be the correct solution. You could also just add `jest` to your project's `package.json`.

**Comment by andys8** [comment]
With `jest` there is likely to be a `jest` key for configuration in the `package.json` or a `jest.config.js` file.
https://jestjs.io/docs/en/configuration

**Comment by codeinabox** [comment]
Is this still an issue?

**Comment by codeinabox** [comment]
This in theory should no longer be an issue because #475 now only checks `dependencies` and `devDependencies` if you have Vim 8 or Neovim and #335 added support for React Scripts. Feel free to reopen this if it's still an issue

**Comment by nomasprime** [comment]
Hi @codeinabox, maybe there's still an issue with this.

I have a bunch of code exercises in subfolders of a repo. When the working directory is an exercise folder it works as expected but when the working directory is the parent repo directory I'm told `"Not a test file"`.

Of course, I can keep updating the working directory but it's not ideal. Thought I'd raise as a potential vim-test improvement.

**Comment by khacluan** [comment]
For me, I install the jest lib in global and set the runer to `jest` and it works for me
```
# terminal
yarn global add jest

# in vimrc
let test#javascript#jest#executable = "yarn test"
let g:test#javascript#runner = 'jest'
```
