### ISSUE TITLE
Can no longer change Mocha suite location

### ISSUE THREAD

**Issue by genericsteele** [vim-test/vim-test#285]
Our js tests live in `/test/javascripts`. I just upgraded my `vim-test` and it seems like since 68ad7d39173b4e39d12f45d41bcd743b815880df  `--recursive test/` is always appended to `TestSuite` for Mocha tests.

Prior to 68ad7d39173b4e39d12f45d41bcd743b815880df, I could run our test suite using this:

```vim
let test#javascript#mocha#options = { 'suite': '"test/javascripts/**/*.js"' }
``` 

Which would generate this command:
```sh
node_modules/.bin/mocha-webpack "test/javascripts/**/*.js"
```

But now, the same configuration gives me this:

```sh
node_modules/.bin/mocha-webpack "test/javascripts/**/*.js" --recursive test/
```

**Comment by janko-m** [comment]
@rumblesan Any ideas how to remedy this?

**Comment by codeinabox** [comment]
@genericsteele thank for the bug report. What happens if you omit your options? Sounds like what you want is an option to override the test directory.

**Comment by rumblesan** [comment]
so I think that the command `node_modules/.bin/mocha-webpack --recursive test/` should be "correct" in that it will still pick up all the tests and will only run those that are js tests right?

Can see that it could be preferable to say have
`let test#javascript#mocha#options = { 'testdir': '"test/javascripts"' }`
and then have the resulting command be `node_modules/.bin/mocha-webpack --recursive test/javascripts`
If there's an issue with having `--recursinve test/` then that would likely be the best fix

**Comment by codeinabox** [comment]
@janko-m sounds like we should have a standard option, maybe for all runners, to allow overriding the tests base path. Thoughts?

**Comment by janko-m** [comment]
I think we should have the test runner detect when an argument referencing test files were given, and then add it as the `--recursive` value instead of the `test/` directory. The Ruby's Minitest runner does this, for example:

```vim
:TestSuite
" bundle exec rake test TEST="test/**/*_test.rb"

:TestSuite test/plugin
bundle exec rake test TEST="test/plugin/**/*_test.rb"
```

Minitest does this by detecting whether any argument is a directory or file, and in that case replaces the default `test/` directory. I think we can do the same for the Mocha runner.

It would be probably more difficult to detect *globs* in addition to directories, but as @rumblesan it might even be preferable to be able to use just directories.

**Comment by codeinabox** [comment]
So to confirm we are saying that @rumblesan should be able to set this option

```viml
let test#javascript#mocha#options = { 'suite': 'test/javascripts/' }
```

Which would result in the following?

`node_modules/.bin/mocha-webpack --recursive test/javascripts/`

**Comment by codeinabox** [comment]
I introduced a flexible pattern in this PR #451 so this should no longer be an issue but feel free to reopen this if it is.
