### ISSUE TITLE
:TestNearest ruby#minitest --name incorrect

### ISSUE THREAD

**Issue by cj** [vim-test/vim-test#311]
When running `:TestNearest` on:

```ruby
# frozen_string_literal: true

require 'test_helper'

class SteppyTest < Minitest::Test
  test 'it has a version number' do
    ::Steppy::VERSION.wont_be_nil
  end
end
```

It generates `bundle exec rake test TEST="test/steppy_test.rb" TESTOPTS="--name='/SteppyTest\#test_it_has_a_version_number$/'"` when it should be `bundle exec rake test TEST="test/steppy_test.rb" TESTOPTS="--name='/SteppyTest\#test_\d+_it has a version number$/'"`

**Comment by janko-m** [comment]
The reason why test.vim builds `test_it_has_a_version_number` is because that works correctly with ActiveSupport's `test` method.

Where is this `test` method coming from? It's not part of Minitest, at least not the version I'm using.
