### ISSUE TITLE
Request: Add Catch2 C++ unit test support

### ISSUE THREAD

**Issue by jamespharvey20** [vim-test/vim-test#366]
Catch2 C++ unit test framework: https://github.com/catchorg/Catch2

Catch2 tests can be given an argument to specify different "reporters" to change the output format, as discussed here: https://github.com/catchorg/Catch2/blob/master/docs/reporters.md

It defaults to console, in human readable form.  But, you can select others such as `junit` which is XML corresponding to Ant's junitreport target, or `xml` which I'm thinking is the best and is XML tailored to Catch.

There's also Visual Studio Code extension that adapts Catch2 and Google Test to VSCode here: https://github.com/matepek/vscode-catch2-test-adapter -- perhaps seeing this will help with my request and #294.  A very brief look at their code makes it look like they just let them run reporting to the console, and parse that output.

**Comment by s7726** [comment]
vim-test has a TAP runner... I recently improved the Catch2 TAP Reporter (it's in the latest release).
Should get you up and running.

**Comment by codeinabox** [comment]
I am also happy to help anyone with a PR when it comes to this feature
