### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by codeinabox** [vim-test/vim-test#371]
I've started using Kotlin and noticed there is no support for it currently in this plug-in. Based on the [Kotlin testing documentation](https://docs.gradle.org/current/userguide/java_testing.html) I was able to quickly put together a test runner which uses Gradle by copying and editing code used by the Java test runner. Should these two share code or is best to keep them separate? Happy to raise a PR based on what I have already

**Comment by connorlay** [comment]
@codeinabox I'm interested in Kotlin support for this library. Do you have a branch or repo I can look at with this working?
