### ISSUE TITLE
Add support for python .feature files

### ISSUE THREAD

**Issue by ngfgrant** [vim-test/vim-test#402]
Firstly, awesome tool thank you!

[`Pytest-bdd`](https://github.com/pytest-dev/pytest-bdd) and [`behave`](https://github.com/behave/behave) enable python based projects to adopt Gherkin/Cucumber tests. As it stands there isn't an identifier for python-based `.feature` files. Would there be appetite to add an identifier for python? I suggest that a good first step would be to supprt `pytest-bdd` as it uses `pytest` as a runner, which is already supported. The `pytest` project also seems a bit more active than behave (last patch release was Feb 2018).

I came across this as the I have setup for vim-test is to `TestNearest` on save in a test file. When I am in my `pytest-bdd` or `behave` projects it tries to execute javascript identifier for `.feature`

```
Error detected while processing function test#exists[1]..test#test_file[1]..test#determine_runner[9]..test#base#test_file[1]..test#javascript#cucumberjs#test_file[2]..
test#javascript#has_package:
line    1:
```

Would there be appetite for this before I attempt a pull request?

**Comment by janko** [comment]
Yes, definitely, feel free to send a PR 👍

**Comment by hnandiwada** [comment]
Are there any plans to support `pytest-bdd` with `:TestNearest`? As far as I can tell, `pytest-bdd` seems to be pretty popular.
