### ISSUE TITLE
Make optional printing spec name before running

### ISSUE THREAD

**Issue by dansdantas** [vim-test/vim-test#411]
Just like clearing screen before running any spec, is there any way to not printing the spec name?

Thanks for your hard work!

**Comment by codeinabox** [comment]
Thank you. Are you referring to a particular test framework or strategy where this happens?

**Comment by dansdantas** [comment]
I am using vimux on rails rspec tests.

I don't know much about vim but from what i understood, it calls this method on `strategy.vim`
```
function! test#strategy#vimux(cmd) abort
  if exists('g:test#preserve_screen') && !g:test#preserve_screen
    if exists('g:VimuxRunnerIndex') && _VimuxHasRunner(g:VimuxRunnerIndex) != -1
      call VimuxRunCommand(!s:Windows() ? 'clear' : 'cls')
      call VimuxClearRunnerHistory()
    endif
    call VimuxRunCommand(s:command(a:cmd))
  else
    call VimuxRunCommand(s:pretty_command(a:cmd))
  endif
endfunction
```

and i end up on the `else` part that calls `pretty_command` and ends calling `echo` on terminal.

I "fixed" by disabling both `test#preserve_screen` and `g:VimuxRunnerIndex` (making less than 1), but i don't know if this is correct.

**Comment by janko** [comment]
Yes, printing commands is not framework-specific, it's implemented on the strategies level, I think it's applied to most strategies. I would probably be useful to have a separate configuration option (e.g. `test#echo_command`, that can be set to `0`) for disabling printing.

If you agree with that, I'd welcome a PR (I don't have time to make one myself unfortunately).
