### ISSUE TITLE
open test in Float term if its available

### ISSUE THREAD

**Issue by gko** [vim-test/vim-test#417]
test if `FloatTermNew` is available and open tests there.

see [floatterm repo](https://github.com/voldikss/vim-floaterm)

**Comment by codeinabox** [comment]
This feels more like a strategy and would make a great pull request, let me know if you'd like a hand with this or if I have time I might create one myself.

**Comment by gko** [comment]
@codeinabox I actually tried to do it, but it seems that FloatTermNew doesn't accept parameters, such as a command to execute. Will have to do a PR there first, or find another way.

**Comment by ellisonleao** [comment]
#507 added the strategy

**Comment by voldikss** [comment]
Hi @codeinabox since #507 has done the PR, I think the issue gets resolved now. You can close it now.
