### ISSUE TITLE
Can't get working with Dispatch and therefore Neomake

### ISSUE THREAD

**Issue by nomasprime** [vim-test/vim-test#423]
Trying to get [this](https://www.dev-log.me/Running_tests_with_vim-test/).

Have installed those plug-ins, except I working with Ruby, and I'm using the following config:

```
nmap <silent> <Leader>tn :TestNearest<CR>
nmap <silent> <Leader>tf :TestFile<CR>
nmap <silent> <Leader>ts :TestSuite<CR>
nmap <silent> <Leader>tl :TestLast<CR>
nmap <silent> <Leader>tv :TestVisit<CR>

let test#strategy = "neomake"

if filereadable('dip.yml')
  function! DipTransform(cmd) abort
    return 'dip '.a:cmd
  endfunction

  let g:test#custom_transformations = {'dip': function('DipTransform')}
  let g:test#transformation = 'dip'
endif
```

This maps to [dip](https://github.com/bibendi/dip) which allows me to run commands in Docker as though they were local.

If I run with an RSpec file, I get a quickfix window but there's a `#` in front of the filename so they're not linked; with Minitest nothing happens at all.

Running with another strategy I get output but I'd rather get this working with Neomake.

No idea what's going on. Hopefully someone can help.

**Comment by nomasprime** [comment]
Have a hunch this is to do with `errorformat`. Nothing's picked up for Minitest and when I use with Rspec it adds `#` in front of the path so the results aren't linked to an actual file.

**Comment by nomasprime** [comment]
https://github.com/janko/vim-test/pull/425

**Comment by nomasprime** [comment]
Not sure why but removing `bundle exec` with `let g:test#ruby#bundle_exec = 0` seems to fix `#` problem with RSpec.

Last problem I have is a bunch of `^@` characters in the output.

**Comment by nomasprime** [comment]
Trying out with local env now to compare performance.

Dispatch doesn't recognise any combination when running Minitest (see https://github.com/tpope/vim-dispatch/issues/291).

Also running RSpec with bundle exec means for some reason the files don't link up for Neomake.

In summary, Ruby test runners with Dispatch and Neomake don't work. Not sure where the problem is though and I need draw a line fairly soon and revert to running tests in a terminal.

**Comment by nomasprime** [comment]
Exhausted my options so going to switch to another strategy for now.

**Comment by janko** [comment]
What is the test command that gets generated by vim-test, and what is the Vim compiler you expected Dispatch.vim to activate? If you're using Neovim, you can see the test command printed out in the terminal window name, while for Vim it should be printed on the shell.

**Comment by nomasprime** [comment]
Test commands for RSpec will either be `bundle exec rspec …` or `./bin/rspec …` depending on the context. Dispatch picks up the latter OK but not the former. However if I run `Dispatch -compiler=rspec …` or add `bundle exec` to Dispatch's compilers, they both work.

Think specifying the compiler's probably the most concise. Maybe vim-test should send this to improve reliability?

With Minitest this was actually partially working, in the same way RSpec is now, when everything was running through Docker but now I moved to local dev it doesn't seem to matter what I do, it doesn't work. The commands are similar except `bundle exec ruby -Itest …` and `ruby -Itest …`. Neither of these work with Dispatch (see issue mentioned above).

Seems first sub-issue could be solved by vim-test. Second could be a problem with Dispatch but no idea why it would partially work with Docker and not at all with local env.

**Comment by nomasprime** [comment]
@janko the last piece to get vim-test working with NeoMake strategy is [here](https://github.com/neomake/neomake/issues/2459).

Have a hunch vim-test should be sending additional args [here](https://github.com/janko/vim-test/blob/master/autoload/test/strategy.vim#L27).

**Comment by nomasprime** [comment]
Been a while since I've looked at this but think the problem was related to [this](https://github.com/tpope/vim-dispatch/issues/291).

Looks like Minitest and RSpec are both working now, closing issue.
