### ISSUE TITLE
Run test until failure 

### ISSUE THREAD

**Issue by ogirginc** [vim-test/vim-test#437]
I just saw this feature on IntelliJ. I think, it would be quite useful for flakey tests. 

https://twitter.com/chrisjenx/status/1232067112727769088

**Comment by codeinabox** [comment]
It's an interesting idea though several things spring to mind:-

- This plug-in is not concerned with whether the tests pass or fail, just executing the correct runner command in the strategy
- To determine if a failure or pass occurred you'd need to use the the MakeGreen strategy and have configured a proper errorformat for the runner 
- I feel like this might be a feature of the actual runner itself, say akin to test watching

My gut feeling is this is beyond the remit of this plug-in but something you could build on top of it. @janko any further thoughts?

**Comment by ogirginc** [comment]
Those are all valid points. Just shared it to start a conversation. :)

That being said, the first thing that come up to my mind was implementing an option for [runner commands](https://github.com/janko/vim-test#runner-commands). However, what I didn't know was this plug-in not being aware of the outcome of the test's result.

**Comment by codeinabox** [comment]
Am closing this for now but feel free to reopen.
