### ISSUE TITLE
Neovim terminal mode

### ISSUE THREAD

**Issue by chinleung** [vim-test/vim-test#448]
Hi,

When I run my tests using the `neovim` strategy, it opens a new terminal but auto focus on the buffer. Then I have to press `<C-o>` to not close the buffer and go back to my split pane.

Is there a way to have it open but not switch my focus to the newly opened pane automatically?

**Comment by codeinabox** [comment]
Good question looking at the code it uses the `termopen` command https://github.com/janko/vim-test/blob/master/autoload/test/strategy.vim#L78

I didn't write the strategy but I'd suggest reading up on how `termopen` behaves and seeing if we can change or configure this.

**Comment by haringsrob** [comment]
```
function! CustomStrategy(cmd)
  execute 'bel 10 new'
  call termopen(a:cmd)
  wincmd p " switch back to last window
endfunction

let test#custom_strategies = {'custom': function('CustomStrategy')}

let test#strategy = "custom"
```

This is how I do this.

**Comment by fwolfst** [comment]
Still an issue :( and nothing in the help about it yet.
