### ISSUE TITLE
Running tests prevent from changing window using Ctrl-keys

### ISSUE THREAD

**Issue by hahuang65** [vim-test/vim-test#462]
When running a test in `vimterminal`, I'm no longer able to change my window using `ctrl-j` or `ctrl-k` to edit my other files while waiting for a test. Is there something I can do about this?

**Comment by janko** [comment]
What was the last version/commit of vim-test where you were still able to do this?

**Comment by hahuang65** [comment]
I just installed this plugin today 🥺

**Comment by codeinabox** [comment]
Couple of questions: 1) Which version of vim are you using? 2) Is this happening for all tests?

**Comment by hahuang65** [comment]
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 13:23:00)
Included patches: 1-510
Compiled by Arch Linux
```

What do you mean by all tests?

My experience is, if I start tests with `vimterminal` as the strategy, it'll start a terminal in a split, and if I try to press, for example, ctrl-k, it'll just print `^k` in the terminal and ignore my actual vim mapping to change window.

I have to wait for the full tests to complete, before I can switch windows (using a ctrl-hotkey). It seems like this MIGHT be intended since the plugin suggests to press `ctrl-c` to quit if tests are still running, so you guys might be forwarding all `ctrl-hotkey` keypresses to the terminal instead of vim?

**Comment by codeinabox** [comment]
When I said all tests I mean does it happen for both TestNearest, TestSuite etc?

When you run the tests does it switch to the terminal split in insert mode? What happens if you run other commands within a terminal - do they also block ctrl-j and ctrl-k?

**Comment by hahuang65** [comment]
Yup, it happens for all tests.

When I run tests, it switches to the terminal split. Any keypresses end up printing to the terminal, so I would assume it's in insert mode.

If I try to use `:` for command mode, it just prints `:` to the screen. It doesn't seem like I can do any vim things until the tests are done running.

I'm able to do a `<C-w>k` in order to change windows, or use the mouse to change windows, but these are not in my normal workflow.

**Comment by hahuang65** [comment]
Just wanted to note here that this is user ignorance.

Needed to add:

```
tnoremap <C-k> <C-w>k
tnoremap <C-j> <C-w>j
tnoremap <C-h> <C-w>h
tnoremap <C-l> <C-w>l
```

so that terminal mode knows what to do when I press those keys.

Feel free to close.
