### ISSUE TITLE
groovy support?

### ISSUE THREAD

**Issue by marene** [vim-test/vim-test#472]
I just started working on a kotlin project that uses groovy and maven for testing
I can't seem to find a way to make vim-test work for groovy files: Is my only solution to write a custom runner for groovy, or is there a way for me to leverage the maven runner that comes stock?

Sorry for the simplistic question, but I must admit I'm feeling at a loss here...

**Comment by codeinabox** [comment]
I had created a similar ticket for #371 for this. I am happy to help implement a solution based on your needs. Could you either create a PR with some spec examples of what you're trying to achieve or add the details to the ticket and we can go from there.

**Comment by marene** [comment]
Thanks for the answer @codeinabox !
I can try, but it won't be right away unfortunately, as I am a bit overwhelmed with work at the moment: I'll try to do it asap thought!

**Comment by marene** [comment]
Okay, so:
The project I'm working on is in kotlin, but uses groovy for the tests, with spock as a test framework.

The tests look like something like:
```
class FoobarSpec extends spock.lang.Specification {

    def "increment a number"() {
        given: "A number"
        def number = 42

        when: "We add one to this number"
        number++

        then: "It should be equal to the original number plus one"
        number == 43
    }
}
```

So I suppose `:TestNearest` should fetch the closest `def` and the next closest `class` to pass it to either maven or gradle (both seem to have similar command line arguments to run one single test case).
Same logic would apply for `:TestSuite`

As I'm writing this (and slowly learning about how java/kotlin environments work, it's my first time ever using these technologies), I realize the logic implemented in the `java` runner seems to apply, except maybe for the [position building functions](https://github.com/vim-test/vim-test/blob/master/autoload/test/java/maventest.vim)
I wonder if it would be possible/clean to refactor those so that `java#mavenTest` runner (and the `java#gradleTest` too I suppose) would be able to run tests in groovy files as well

@codeinabox please tell me if I'm not being clear (I must admit that my thought process is a bit foggy even for me, I really am a newbie with jdk environments, my apologies)

**Comment by codeinabox** [comment]
What CLI commands would you expect it to generate for test file, nearest etc for the example you have given?

Currently the Maven runner will generate commands like `mvn test -Dtest=org.vimtest.math.TestMath\*` and my Kotlin branch generates things like `gradle test --tests AppTest`

**Comment by marene** [comment]
For this example, I would run it like so:
 * `:TestNearest`: `$> mvn -Dtest=FoobarSpec#"increment a number" test`
 * `:TestSuite` : `$> mvn -Dtest=FoobarSpec test`
 * `:TestFile` : I actually m not too sure, never had the use for this command tbh

So basically the same way as the `java#mavenTest` runner, the only specific would be finding the

**Comment by dansomething** [comment]
@marene I believe [this code](https://github.com/dansomething/dot_vim/blob/master/.vim/autoload/test/groovy/maventest.vim) may interest you. Unfortunately, I haven't had the time to polish it up in order to deem it worthy of a PR here, with automated tests and so on, but it does work (for me anyway).

See https://github.com/vim-test/vim-test#extending

You would enable it like so:
```viml
let test#custom_runners = {'Groovy': ['Maventest']}
```

**Comment by marene** [comment]
@dansomething damn I had absolutely forgotten about that issue!!
Thanks a bunch, I'll give it a try over the weekend!

**Comment by grational** [comment]
It could be nice to have support for the Spock Specification files. It is one of the best test frameworks out there.
