### ISSUE TITLE
Travis pipeline broken on rvm install

### ISSUE THREAD

**Issue by codeinabox** [vim-test/vim-test#497]
I am getting the following error on Travis builds such as https://travis-ci.org/github/vim-test/vim-test/builds/711031309

> The command "rvm use 2.5.8 --install --binary --fuzzy" failed and exited with 1 during .

@janko any pointers on how to fix this?

**Comment by janko** [comment]
Seems like maybe a recent version of RVM (a Ruby version manager) has a bug with installing Rubies. Could you try bumping the Ruby version in `.travis.yml` to `2.6.5` and see if that fixes the issue?
