### ISSUE TITLE
Do you want a runner for TestBench?

### ISSUE THREAD

**Issue by tomdalling** [vim-test/vim-test#498]
I've been using [TestBench](http://test-bench.software/) (Ruby testing framework) recently, and I've written a [custom runner for it](https://github.com/tomdalling/config/blob/cca96cfa57dfd44533f86a0fd0541ae0491236cb/nvim/autoload/test/ruby/testbench.vim). Is that something you would want merged in to Test.vim? If so, I can make a PR.

**Comment by codeinabox** [comment]
That would be fantastic if you could! Please add some spec and fixtures to accompany it and give me a shout if you need help with the latter.

**Comment by tomdalling** [comment]
Ok, cool. I'll open a PR shortly. 👍
