### ISSUE TITLE
phpunit - when paratest is installed, all other executables break when using TestNearest

### ISSUE THREAD

**Issue by jessarcher** [vim-test/vim-test#501]
#480 introduced code so that when `paratest` is detected (by checking for the presence of `./vendor/bin/paratest`) it prepends `--functional ` to the test name, regardless of whether `paratest` is the executable.

https://github.com/vim-test/vim-test/blob/master/autoload/test/php/phpunit.vim#L28-L30

This causes other executables to choke with an `unrecognized option --functional`

In my case, `paratest` is installed to make CI builds faster because it runs multiple tests in parallel. However for local development it can make debugging harder because it seems to swallow `stdout` so things like `dd()` can't be used. I would prefer to use standard `phpunit` (or the improved output of `php artisan test` as mentioned in #445), especially for `TestNearest`, but currently this code is making that not possible.

I'm happy to submit a PR for this, but I'm not familiar enough with the architecture of this (or vimscript) to know the best way to prevent the bug that #480 solved, while also allowing different executables to be used when `paratest` is present.

**Comment by jessarcher** [comment]
@codeinabox I would appreciate your input on this if you have time :)

**Comment by codeinabox** [comment]
Thank you for raising this issue. At the moment the current behaviour is to use paratest over phpunit if both are present.

How would you like this behaviour to work? I was thinking that we could allow the user to override the executable eg `let test#php#phpunit#executable = 'php artisan test'` and that the runner only adds `--functional` if the executable is paratest

**Comment by jessarcher** [comment]
Thanks for replying!

That sounds great to me. Keeping paratest as the higher priority makes sense and I'm happy to override it as needed.

I might have a go at implementing this over the weekend unless you beat me to it.

**Comment by codeinabox** [comment]
Great, I already have a small work in progress and will let you know when it's ready to review.

**Comment by codeinabox** [comment]
A heads up I was quickly able to create a fix for this so please give that branch a test.

**Comment by jessarcher** [comment]
That's perfect, thanks!
