### ISSUE TITLE
rspec files that begin with test_ trigger minitest

### ISSUE THREAD

**Issue by fakeharxy** [vim-test/vim-test#503]
I know this will be very easy to solve, you have given the tools to do so, but I can't figure it out.

Test files that begin test_ (for example, test_order_spec.rb) don't get picked up as rspec even though, in my case, they are.

I've tried:

```let test#ruby#rspec#file_pattern = '_spec\.rb'```
```let g:test#runner_commands = ['RSpec']```

but neither had any effect. How do I ensure ALL my test files run as if they were rspec?

Thanks!

**Comment by codeinabox** [comment]
Is the issue that at the moment they are run with Minitest?

**Comment by fakeharxy** [comment]
yes, sorry, for all my other tests, vim-test produces something like:
```./bin/rspec spec/models/some_spec.rb``` 
but for tests that begin test_ it produces something like:
```/bin/rake test TEST="spec/models/test_order_spec.rb"```

which raises the error:
```
rake aborted!
Don't know how to build task 'test' (See the list of available tasks with `rake --tasks`)
```

**Comment by codeinabox** [comment]
For some reason it's getting picked up by the minitest runner so what I'd suggest, at least as an interim measure, is to also change the pattern for `test#ruby#minitest#file_pattern` to something that won't match your tests.

**Comment by fakeharxy** [comment]
ah great, that worked, thanks.

For completeness, if anyone finds this, I solved this by:

`let test#ruby#minitest#file_pattern = '_zzzzzz\.rb'`
