### ISSUE TITLE
How to use it with Ruby ? ( Error detected while processing )

### ISSUE THREAD

**Issue by rusikf** [vim-test/vim-test#527]
Hi, I set up vim-test
and run

> :TestNearest

 
in my RSpec file ( Ruby test )

> Error detected while processing function test#run[5]..test#test_file[1]..test#determine_runner:
> line    9:
> E117: Unknown function: test#base#test_file
> Press ENTER or type command to continue
> 
>

**Comment by fractalic** [comment]
Interesting... I'm seeing the exact same error when trying to run xUnit tests.

**Comment by rusikf** [comment]
I setup ale plugin, which run rubocop/eslint etc without problems
https://github.com/dense-analysis/ale
