### ISSUE TITLE
Issue on subsequent runs with vimux

### ISSUE THREAD

**Issue by craigp** [vim-test/vim-test#550]
When initially running tests, everything works perfectly. On subsequent runs, irrespective of the command, it seems to fail with `Unknown function: _VimuxHasRunner`

![image](https://user-images.githubusercontent.com/9042/111252237-c848d500-8664-11eb-8779-f24bce0a5def.png)
![image](https://user-images.githubusercontent.com/9042/111252262-d696f100-8664-11eb-9e7f-ac834732440b.png)

EDIT: I've switched to VTR and that's working fine, I suspect something changed in vimux

**Comment by klaaspieter** [comment]
Vimux removed the `_VimuxHasRunner` function in favor of [`hasRunner`](https://github.com/preservim/vimux/commit/29c5b395458172c33f141ed788b04c8674173701#diff-6b0bbd57d2f0b3ef4ffd0dc57a62752584a28d205595805cb6aca6ed8084c46bR242-R245).
