### ISSUE TITLE
Cypress nearest not working

### ISSUE THREAD

**Issue by chris542** [vim-test/vim-test#560]
When i run :TestNearest, it runs the entire single file instead of the nearest single test method. :(

**Comment by slobodan-ilic** [comment]
What's the name of the test? Maybe you can tweak it by specifying additional patterns [here](https://github.com/vim-test/vim-test/blob/206eb5492b4afa03c31cea529aa917b4a7085d10/autoload/test/javascript.vim#L2). That's what I did for python in the appropriate file (check out the #559).

**Comment by chris542** [comment]
@slobodan-ilic 

I realised when I have both Jest and Cypress tests installed in my package.json, it always picks Jest. Is there any way to decide which test library i want to run?

**Comment by CallumHoward** [comment]
Did you find a way?

**Comment by chris542** [comment]
@CallumHoward no sorry. sorry for the late response. I'm currently testing cypress with 

```
nmap <silent> <leader>to :Cypress open -C ./*/**/cypress.json<CR>
```
and manually click the UI.. :( 
My team is deprecating usage of Cypress and moving on to Playwright which uses Jest instead, so hopefully i don't have to test Cypress anymore..
