### ISSUE TITLE
Probably Newbie Question: executing TestSuite always results in  a message "Not a test File"

### ISSUE THREAD

**Issue by ghorsey** [vim-test/vim-test#570]
It's a really simple setup.  I'm actually following along with the modern vim book.  (I've been using vim emulation on IDEs for years and want to fully dive in).

Anyway, my project structure is: 
* jasmint-test
  * lib/
    * homophoner.js
  * node_modules/
  * spec/
    * Support/
      * jasmine.json
    * homophonerSpec.js
  * .gitignore
  *  package.json

Opening the homophonerSpec.js file and running the `:TestSuite` command outputs the message "Not a test file"

Note:
I only have jasmine installed locally in the package.json file.

```
{
  "name": "test-jasmine",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "private": true,
  "scripts": {
    "test": "jasmine"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "jasmine": "^2.8.0",
    "lodash-node": "^3.10.2"
  }
}
```

I've tried going through the README, but I cannot find anything that I'm supposed to do.  I must be missing a dependency.

I've tried in both vim and nvim wth the same result.

**Comment by anurag2947** [comment]
Try renaming file to include word **test** like
homophonerSpec_test.js
test_homophonerSpec.js
homophoner_test_Spec.js

**Comment by ghorsey** [comment]
I tried renaming it to homophonerSpec_test.js and the same effect, the same, not a test message, occurred.

I am also using nvim from a windows terminal. I'm not sure if that'd make a difference.

**Comment by ghorsey** [comment]
I'm still trying to figure this out.  I started writing out some logs and `g:test#runner_commands` variable is an empty array.

I added the `let g:test#runner_commands = ['Jasmine']`


Now that I added the jasmine runner command, `:Jasmine` is added and works and runs all the tests.

However, the commands `:TestSuite` and `:TestNearest` commands still fail with the "Not a Test File" message

**Comment by ghorsey** [comment]
Not sure what's going to happen here, but I found two bugs in the jasmine.vim when running on windows.

The first issue is with the regex https://github.com/vim-test/vim-test/blob/4eb72005f87ff1bf3bc7e523b176bd6b391f6e24/autoload/test/javascript/jasmine.vim#L2
The problem here is that on windows the directory separator is a `\` so the RegEx never matches on windows.

The second issue is with selecting the jasmine executable here https://github.com/vim-test/vim-test/blob/4eb72005f87ff1bf3bc7e523b176bd6b391f6e24/autoload/test/javascript/jasmine.vim#L41

Again the issue is because windows does not use a `/` as the path separator.

I have fixes for both of these and I'll raise a PR shortly.

The workaround for this is to set the following values in your vimrc

```
let g:test#javascript#jasmine#file_pattern = '\v^spec[\\/].*spec\.(js|jsx|coffee)$'
let test#javascript#jasmine#executable = 'npx jasmine'
```

**Comment by ghorsey** [comment]
I raised this PR #571  to fix this, but I don't know that I am able to link PRs and Issues.
