### ISSUE TITLE
Include groupId in maventest

### ISSUE THREAD

**Issue by andrewwillette** [vim-test/vim-test#594]
Executing tests in a maven reactor solution of mine fails if -pl argument does not specify groupId, ie 
`-pl groupId:artifactId`.

If groupdId is not specified, the tests fail with `[ERROR] Could not find the selected project in the reactor... `. Including the groupId causes the test to correctly run.

Sorry, I couldn't find any discussion about this.

**Comment by GiuseppeMP** [comment]
@andrewwillette Hello!

Could you explain how to reproduce this issue?

**Comment by andrewwillette** [comment]
@GiuseppeMP sorry, it's been a long time since I've worked on maven solutions such as what brought this up. I'm going to close this issue.

The problem arose from a complex module structure I don't have on my machine anymore (enterprise software of former employer).
