### ISSUE TITLE
Kotlin backtick surrounded function names

### ISSUE THREAD

**Issue by marcelja** [vim-test/vim-test#600]
`:TestNearest` is testing the entire file when I have function names that are surrounded with backticks.

Example:
``` kotlin
fun `test something, 123-456`() {
  // test
}
```

Would it be possible to make this work? I'd be happy to update this regex https://github.com/vim-test/vim-test/blob/2052bd926c37b5c828dd07c47ac676102ca34a0e/autoload/test/kotlin.vim#L4

The gradle command would not work with backticks though.
```
./gradlew test --tests ExampleTest.`test something, 123-456`
```
I guess that `` ` `` needs to be replaced by `"` somehow.

**Comment by codeinabox** [comment]
Could you put together some examples, either in this issue or ideally creating a PR and updating the specs. Happy to give a hand with this

**Comment by marcelja** [comment]
I created the PR #601

**Comment by codeinabox** [comment]
Thank you, this has now been merged in
