### ISSUE TITLE
C# tests doesn't condsider powershell as a terminal

### ISSUE THREAD

**Issue by MrFisher404** [vim-test/vim-test#618]
I changed my vim shell to powershell therefore the if statement 
`let s:slash = (has('win32') || has('win64')) && fnamemodify(&shell, ':t') ==? 'cmd.exe' ? '\' : '/'`
in vim-test/autoload/test/csharp.vim makes the wrong slash. Here powershell should be considered as well

**Comment by erietz-werner** [comment]
I also have this issue. I have set my shell to powershell using the exact configuration provided in `:help shell-powershell` in neovim and running the nearest test results in a series of errors. This plugin works fine if I set the shell back to cmd.
