### ISSUE TITLE
Detect Java Runner by Files Present in Root Directory

### ISSUE THREAD

**Issue by cloudlena** [vim-test/vim-test#621]
Wouldn't it be possible to detect the appropriate Java by the files present in the workspace's root directory? E.g., if there's a `settings.gradle` file, use Gradle and if there's a `pom.xml` file, use Maven. To me, that seems more user-friendly than users having to set `test#java#runner` manually.

**Comment by GiuseppeMP** [comment]
It also seems to be resolve in this branch: https://github.com/GiuseppeMP/vim-test/commit/ad515fd4ddec12930ee2f63e82873b20c5f9f718

But I need to merge the #662 before it.

**Comment by GiuseppeMP** [comment]
[update]
Now it's working for maven as well, just waiting to open merge request.

Fixes: https://github.com/GiuseppeMP/vim-test/tree/issue-621-maven-runner-based-pom-xml-presence

**Comment by GiuseppeMP** [comment]
@codeinabox @cloudlena Hey!

I believe this issue can be closed, right?

**Comment by codeinabox** [comment]
I shall close this but feel to reopen.
