### ISSUE TITLE
TestNearest Doesn't Run for Tests With Nested Quotes & Backslashes

### ISSUE THREAD

**Issue by trisys3** [vim-test/vim-test#625]
I'm using `vim-test` with the `jest` runner.

I think I found an edge case for the TestNearest regex engine, but I'm not sure. I assume the edge case is for all test runners, but it could just be for `jest`.

In running `:TestNearest` inside a test where the name is single-quoted, and where there is a single quote in the name (meaning you had to escape the quote with a backslash), the regex used seems to have too many backslashes, so `jest` can't find the test. If I remove the backslash & quote, `jest` is able to find the test.

The backslash can be in the `describe` or the `it`. Examples of names I've tried that _don't_ work are:

```
describe('doesn\'t have a test'
it('shouldn\'t be enabled'
```

If you need any more info, please ask.

**Comment by akivajgordon** [comment]
I noticed that this fails also if the test name has parentheses as well:

```ts
test('foo (bar) baz'), t => {...})
```

The output shows that the parentheses are getting escaped, which is probably why the ava cannot find the match.

**Comment by trisys3** [comment]
I don't know Ava, but it looks like the 2nd end paren closes the first paren. If this is not the case, please ignore.

**Comment by akivajgordon** [comment]
@trisys3 thanks - that was just my typo. I've fixed that in the sample code now, but the actual issue still exists.
