### ISSUE TITLE
Nested tests fail in Java JUnit

### ISSUE THREAD

**Issue by cloudlena** [vim-test/vim-test#627]
I'm using nested tests in Java using JUnit's `Nested` annotation: https://junit.org/junit5/docs/5.4.1/api/org/junit/jupiter/api/Nested.html. When running those tests with `:TestNearest`, they fail. However, when I run them with `:TestFile`, they succeed. The same tests were working with vim-test before I introduced the `Nested` pattern.

Here's the output of `:TestNearest`:

```txt
> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [EntityTest.GetSpecificReservableBlock.getsReservableBlock](--tests filter)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
5 actionable tasks: 2 executed, 3 up-to-date

[Process exited 1]
```

The pattern `EntityTest.GetSpecificReservableBlock.getsReservableBlock` seems to be wrong because when I run `gradle test --tests EntityTest.GetSpecificReservableBlock.getsReservableBlock`, I get the same result.

My test file looks as follows:

```java
class EntityTest {

	@Nested
	class GetSpecificReservableBlock {

		@Test
		void getsReservableBlock() { ... }
      }
}
```

The correct pattern would be `EntityTest$GetSpecificReservableBlock.getsReservableBlock` (with a `$` instead of a `.` between the main class and the nested one).

**Comment by GiuseppeMP** [comment]
Hello @cloudlena
I'm also facing this issue, I'm have never contributed to this repository before, so I started with some specs about `@Nested` tests, could you help me to validate the correct output?

See this spec:

https://github.com/vim-test/vim-test/compare/master...GiuseppeMP:master#diff-54917040ad12d6d52d470b7f7c18283ae3938e96febc27fce761c6cbfeffe2f0R19




https://github.com/vim-test/vim-test/compare/master...GiuseppeMP:master#diff-54917040ad12d6d52d470b7f7c18283ae3938e96febc27fce761c6cbfeffe2f0R19

**Comment by GiuseppeMP** [comment]
@cloudlena It seems to be resolved in this merge request, but need to be merged yet. See #662

**Comment by GiuseppeMP** [comment]
@cloudlena Hey, It was merged, could you test and update the issue status? ✌️

**Comment by cloudlena** [comment]
@GiuseppeMP, I'm currently not working with Java so I cannot try the fix... Thanks so much for looking into it! For me, the issue can be closed.
