### ISSUE TITLE
Update to Ginkgo v2

### ISSUE THREAD

**Issue by carlosonunez** [vim-test/vim-test#632]
`ginkgo/v2` has deprecated `--regexScansFilePath` and uses `--focus-file` instead of `--focus`. I've created a PR to address; please see #631 for more info.

Thank you for this amazing plugin!

**Comment by codeinabox** [comment]
Thank you for your kind words. Is this still an issue now that https://github.com/vim-test/vim-test/pull/631 has been merged in?

**Comment by carlosonunez** [comment]
It is not! Thanks again.

**Comment by codeinabox** [comment]
Glad to hear it, I shall close this issue then

**Comment by Skarlso** [comment]
So.... this breaks the v1 flow though, it complains as follows:

```
flag provided but not defined: -focus-file
Ginkgo Version 1.16.5
```

**Comment by carlosonunez** [comment]
that should go away if you update to ginkgo v2
