### ISSUE TITLE
Cannot find test cases using nx runner 

### ISSUE THREAD

**Issue by perfectspr** [vim-test/vim-test#633]
Nx cannot find test causes because it use the default project name. 
Below solution can automatically find the correct project for a test file. 

```vim
function! test#javascript#nx#build_position(type, position) abort
  let project = ''
  if filereadable('workspace.json')
    let l:workpaces = readfile('workspace.json')
    if exists('*json_decode')
      let l:projects = json_decode(join(workpaces, ''))['projects']
      for [key, value] in items(projects)
        if stridx(a:position['file'], value['root']) >= 0 
          let project = key
          break
        endif
      endfor
    endif
  endif

  if a:type ==# 'nearest'
    let name = s:nearest_test(a:position)
    if !empty(name)
      let name = '-t '.shellescape(name, 1)
    endif
    return [project, name, '--test-file', a:position['file'], '--no-coverage']
  elseif a:type ==# 'file'
    return [project, '--test-file', a:position['file'], '--no-coverage']
  else
    return [project, '--no-coverage']
  endif
endfunction
```

**Comment by jponc** [comment]
Haven't tested the solution yet but yeah I'm having issues with NX + vim-test as well...

I'm getting

<img width="775" alt="image" src="https://user-images.githubusercontent.com/4714727/160743215-cf938ff4-ef84-4c03-b76a-c790e126e52c.png">

I'm not sure if it's related though..

**Comment by phantomwhale** [comment]
That fixed it up for me! You should put that into a Pull Request :)

**Comment by jponc** [comment]
Thanks for replying back @phantomwhale , do you happen to know what configuration I should do so it automatically detects it's an nx project instead of a usual JS?

**Comment by excalios** [comment]
I had to tweak the code a bit to work on mine `value['root']` would show the first character only. So I had to change it to use `value` instead.

**Comment by codeinabox** [comment]
Closing this as a solution has been merged in. Feel free to reopen if it doesn't resolve the issue
