### ISSUE TITLE
Setting Options within a NeoVim `init.lua`

### ISSUE THREAD

**Issue by forrestfwilliams** [vim-test/vim-test#642]
I'd love to use this plugin with my NeoVim configuration, but I'm using an `init.lua` setup and not an `init.vim` is there any way to set options like `test#python#runner` inside of an `init.lua`? Thanks!

**Comment by frdrkolsson** [comment]
You could probably do something like this
```lua
vim.g['test#python#runner'] = 'some_value'
```
Check [`:help lua-vim-variables`](https://neovim.io/doc/user/lua.html#lua-vim-variables) if you want more details.
Also check out this guide for another explanation https://github.com/nanotee/nvim-lua-guide#using-meta-accessors-1

**Comment by callumacrae** [comment]
tested, the above works great!
