### ISSUE TITLE
Unable to run jest tests

### ISSUE THREAD

**Issue by atulpatildbz** [vim-test/vim-test#679]
Hi.
I'm using NVIM v0.7.0, just installed this plugin. 
When i run `TestSuite` on a `.test.js` file, I'm getting the following error. 
```
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
```

My OS is windows. Could that be causing any problems?
Not sure if i'm doing something wrong.

**Comment by codeinabox** [comment]
I wonder if this a directory path issue for windows though if it can't read the path then it would default back to `jest`

**Comment by adam-r-kowalski** [comment]
I have this issue on windows as well. You need to add the following:

```
let g:test#javascript#runner = 'jest'
let test#javascript#jest#executable = 'npm test --'
```

**Comment by atulpatildbz** [comment]
Thanks @adam-r-kowalski. That worked for me. Closing this issue.

Is this documented somehwere?

**Comment by codeinabox** [comment]
> I have this issue on windows as well. You need to add the following:
> 
> ```
> let g:test#javascript#runner = 'jest'
> let test#javascript#jest#executable = 'npm test --'
> ```

This is a work around as it's overriding the test detection and configuring it to use the npm script instead so we should fix this issue. I wonder if it's node module binaries are handled differently on Windows 🤔
