### ISSUE TITLE
Reuse existing terminal for Neovim strategy

### ISSUE THREAD

**Issue by dkaszews** [vim-test/vim-test#707]
I would like to be able to keep reusing the same terminal using Neovim strategy, so that my splits don't move around.

It should be doable by opening terminal in interactive shell mode instead of command mode, so that it does not terminate after the command finished, then sending commands to it using `:put ='test'` trick.

One issue might be how to detect if the terminal is ready to run tests again, as running a command while tests are running will likely swallow the input, while running `^C` after tests are finished will terminate the shell.

**Comment by crzdg** [comment]
Would love to see this too!

**Comment by crzdg** [comment]
@dkaszews Thanks a lot! Looks great!

**Comment by dkaszews** [comment]
@crzdg Glad to hear that, let me know if you run into any issues

**Comment by robotbill** [comment]
Thank you, this is awesome! I made a PR to have it optionally re-open the terminal buffer if it's hidden: https://github.com/vim-test/vim-test/pull/770
