### ISSUE TITLE
Test pipeline is not running

### ISSUE THREAD

**Issue by codeinabox** [vim-test/vim-test#714]
I've noticed that the test pipeline on Travis CI hasn't run for about two weeks

**Comment by codeinabox** [comment]
Hello @janko have you got any thoughts or opinions on? I am wondering if switching to Github Actions is the answer, as I believe it's free for public repositories whilst Travis CI has limitations on free plans

**Comment by janko** [comment]
Yeah, I already moved all my other open source projects from Travis CI to GitHub Actions, I think it's the way to go here as well 👍🏻

**Comment by codeinabox** [comment]
I've managed to get it working with Travis CI, though have created another issue to migrate to Github Actions #715 715
