### ISSUE TITLE
Make `ts-node/register` optional in Mocha

### ISSUE THREAD

**Issue by mikaoelitiana** [vim-test/vim-test#717]
Is it possible to make the use of `ts-node` optional. On one of my project, `ts-node` package is installed but is not configured for tests, so some types declarations are breaking, as well as some path aliases. Running mocha test commands without it works well for me so maybe adding a flag variable may be used instead?

https://github.com/vim-test/vim-test/blob/16a3b6da1bab42473d42d7e02d89d549d7a5e138/autoload/test/javascript/mocha.vim#L47-L49

**Comment by codeinabox** [comment]
One thing I meant to ask, is it possible to do this automatically by inspecting the Mocha section in `package.json` or `.mocharc.json` instead? The goal of vim-test is zero configuration for running tests

**Comment by mikaoelitiana** [comment]
> One thing I meant to ask, is it possible to do this automatically by inspecting the Mocha section in `package.json` or `.mocharc.json` instead? The goal of vim-test is zero configuration for running tests

I am not sure to understand what you mean. You think we could check in mocha configuration if it uses `ts-node` or not?

**Comment by codeinabox** [comment]
That's right, in the same way vim-test checks package.json for determining the JavaScript / TypeScript test framework
