### ISSUE TITLE
Display warning if test file has unwritten changes

### ISSUE THREAD

**Issue by andrew-cybsafe** [vim-test/vim-test#723]
I'd like vim-test to display a warning if the test file I'm in has unsaved changes. I know that I can use the autowrite option, but running `:wall` here seems a bit aggressive for my liking. So I propose:
- a new setting `let g:test#warn_if_unsaved_changes = 1`
- a new test in `s:before_run()` which displays a warning to the user if the file isn't saved
- document setting in help docs & readme

As a possible extension, the message could wait for user input to either save the current file, save all files, run it anyway or abort.

I'm happy to give this a go, but wanted to get thoughts from the maintainers before doing so.

**Comment by codeinabox** [comment]
Let me have a think about this and get back to you

**Comment by andrew-cybsafe** [comment]
@codeinabox any thoughts on this?

**Comment by codeinabox** [comment]
Would this only apply to the test file when running `TestFile`?  Would it also apply to the source file, and if so how would we detect which unsaved changes impact the test and which don't?

**Comment by codeinabox** [comment]
If this is a behaviour that will just apply to `TestFile` then it's a viable option. It's got me thinking instead of a prompt, it could save a temporary copy of the test file with the unsaved changes and test against that if the user has enabled an option, in short testing against the buffer instead of saved file - what do you think?

**Comment by andrew-cybsafe** [comment]
Running the test against the version in the buffer would be really nice. However, making this work reliably across all the various test runners might be quite awkward. For example, with pytest the following file name schemes don't work:
```
test_subject.py.tmp
.tmp.test_subject.py
test_subject.vim_123.py
```
The name `vimtest_123.py` does work. However, this scheme might not work for other test runners.

We may need to provide a default naming scheme, e.g. `vimtest_NNNNN.{original extension}`, but allow each runner to override this by defining a function that we look for that optionally overrides the test name creation logic.

**Comment by andrew-cybsafe** [comment]
@codeinabox can you take a look at the small PR I've opened for adding a prompt?
