### ISSUE TITLE
toggleterm strategy doesn't work for golang

### ISSUE THREAD

**Issue by msvitok77** [vim-test/vim-test#728]
Hi all, I've tried the `toggleterm` strategy for my golang tests. But it doesn't work - as the single quotes are misinterpreted. I've fixed it with simple change -> vim-test/autoload/test/strategy.vim:101 

`
  execute "TermExec cmd='".substitute(a:cmd, "'", '"', "g")."'"
`

But there is not quidelines how to become a contributor and create a PR

**Comment by codeinabox** [comment]
Thank you for spotting this issue. As for contributing, it's just a simple case of raising a PR with your small change. Let me know if you have any more questions

**Comment by msvitok77** [comment]
Here is the PR: https://github.com/vim-test/vim-test/pull/753

**Comment by codeinabox** [comment]
Thank you, just merged it in!
