### ISSUE TITLE
Test execution timeout

### ISSUE THREAD

**Issue by mahmoudhossam** [vim-test/vim-test#734]
Vim-test currently runs tests until completion, even if this will take forever.

There should be a timeout option where execution will be canceled if it exceeds this timeout, printing the results so far.

**Comment by codeinabox** [comment]
This very much depends on the test runner as each of them will have a different option for test timeouts. For example the [timeout option in Jest](https://jestjs.io/docs/cli#--testtimeoutnumber), so in this case if you wanted to set a timeout you could do `:TestSuite --testTimeout=5000`

Which test framework were you using where the tests could take forever?

**Comment by mahmoudhossam** [comment]
> This very much depends on the test runner as each of them will have a different option for test timeouts. For example the [timeout option in Jest](https://jestjs.io/docs/cli#--testtimeoutnumber), so in this case if you wanted to set a timeout you could do `:TestSuite --testTimeout=5000`
> 
> Which test framework were you using where the tests could take forever?

I was using Go, but you're right that this is going to be runner-specific.

I'll check the documentation for my test runner, thanks!
