### ISSUE TITLE
Vitest and dispatch not working together

### ISSUE THREAD

**Issue by theTechGoose** [vim-test/vim-test#742]
Vitest is returning ansi escape characters to make colored output however dispatch is incapable of rendering this as it is just a regular quickfix window.

How can we get vimtest to strip these?

|| 
||  RUN  v0.33.0 /Users/goose/Documents/programming/rofer/ami
|| 
|| stdout | src/app.controller.spec.ts > AppController > root > should work
|| hello 
|| 
|| stdout | src/app.controller.spec.ts > AppController > root > should work
|| [ Document { pageContent: [32m'do working39m, metadata: { id: [33m2[39m } } ]
|| 
||  ✓ src/app.controller.spec.ts  (3 tests | 2 skipped) 2423ms
|| 
||  Test Files  1 passed (1)
||       Tests  1 passed | 2 skipped (3)
||    Start at  10:09:48
||    Duration  2.77s (transform 31ms, setup 0ms, collect 134ms, tests 2.42s, environment 0ms, prepare 52ms)
||

**Comment by codeinabox** [comment]
Thank you for reporting this. Does Vitest have an option for ANSI escape characters? I can't see one in the config options https://vitest.dev/config/

**Comment by codeinabox** [comment]
I've merged in a change #743 that will add `--no-color` if the terminal doesn't support it. Could you let me know if it fixes your issue.

**Comment by theTechGoose** [comment]
Sure thing! I'm currently at work and this is a personal project so I'll boot it up as soon as I get a break.

**Comment by codeinabox** [comment]
My changes should have fixed this issue, so I am going to close it for now, but please reopen it if you have issues.
