### ISSUE TITLE
Go test with build tags doesn't run if the tag doesn't have a space

### ISSUE THREAD

**Issue by ivaaaan** [vim-test/vim-test#751]
I have a typical Go project with build tags in tests. For some reason, tests without space after `//` in Go tag do not work:

```go
//go:build unit_test

package tests

import "testing"

func TestTarget2(t *testing.T) {
	t.Fail()
}
```

Outputs

```
ok      github.com/test/test (cached) [no tests to run]
[Process exited 0]
```

However

```go
// go:build unit_test

package tests

import "testing"

func TestTarget(t *testing.T) {
	t.Fail()
}
```

Runs as expected:
```
--- FAIL: TestTarget (0.00s)
FAIL
exit status 1
FAIL    github.com/test/test 0.182s

[Process exited 1]
```

I have tried it with all commands, `TestFile`, `TestNearest`, etc. Not sure what is the possible problem. For `vim-test` I use any standard configuration. 

vim-go plugin has this option:
`vim.g.go_build_tags = "unit_test,integration_test"`

And LSP is configured with `GOFLAGS = "-tags=integration_test,unit_test"`.

CLI run works fine:

```
$ go test -tags="unit_test" ./...                                                                                                                                                                          00:18:38
--- FAIL: TestTarget (0.00s)
--- FAIL: TestTarget2 (0.00s)
FAIL
FAIL    github.com/test/test 0.306s
FAIL
```

I will be happy to assist with a PR if someone points me to where the problem might be

**Comment by codeinabox** [comment]
Hello, thank you for reporting this bug and offering to assist with a PR. I'd recommend the following steps:

1. Add another fixture to cover tests without space after //,  eg `spec/fixtures/gotest/build_tags_test_nospace.go`
2. Add some more tests to `spec/gotest_spec.vim` testing against that fixture
3. Then to get those tests passing it's a case of tinkering in `autoload/test/go/gotest.vim`

**Comment by felix-kaestner** [comment]
> Hello, thank you for reporting this bug and offering to assist with a PR. I'd recommend the following steps:
> 
> 1. Add another fixture to cover tests without space after //,  eg `spec/fixtures/gotest/build_tags_test_nospace.go`
> 2. Add some more tests to `spec/gotest_spec.vim` testing against that fixture
> 3. Then to get those tests passing it's a case of tinkering in `autoload/test/go/gotest.vim`

Hey @codeinabox I followed these steps and created a PR to fix the issue. :)
