### ISSUE TITLE
cypress testnearest support missing

### ISSUE THREAD

**Issue by jonworek** [vim-test/vim-test#755]
This issue is basically a clone of https://github.com/vim-test/vim-test/issues/560 but since that didn't seem to come to a resolution, I wanted to reopen it.

I'm running cypress tests with TestNearest. And as mentioned in the linked issue, every test in the file is being executed rather than the current cursor position. 

Perhaps cypress CLI doesn't include this ability though? I'm relatively new to cypress so maybe it's not possible. A quick duckduckgo search led me to this https://stackoverflow.com/questions/55054337/cypress-run-only-one-test which suggests maybe the only way to do this is by editing the file to include `.only` on the spec.

Maybe TestNearest can somehow achieve its goal with cypress by leveraging that function and making a temporary edit to a test file? I might try to hack at it and see what I can get to work, but perhaps someone else out there has a better suggestion, or has more experience with vim scripts that they could easily implement this.

Thanks, all.

**Comment by codeinabox** [comment]
Reading through the [Cypress CLI guide](https://docs.cypress.io/guides/guides/command-line) I couldn't see an argument or feature that would make test nearest possible

**Comment by codeinabox** [comment]
Closing this issue as it's a limitation of Cypress, feel free to reopen if the Cypress CLI add supports for test filtering
