### ISSUE TITLE
Feature: support for dispatch Spawn

### ISSUE THREAD

**Issue by lisamburns** [vim-test/vim-test#756]
I have been using Vim8 with vim-test for a while using the default basic strategy which is great. I wanted to run my tests non-blocking while still be able to navigate the code, so I tried Dispatch strategy. That allows me to continue to navigate the code, but now I can no longer stop at breakpoints to debug. The Dispatch recommendation is to use Spawn instead of Dispatch as the command.
https://github.com/tpope/vim-dispatch/issues/319

Could vim-test add support for this?
I read through the other options and it wasn't clear that any of the other strategies that are supported would meet desire for non-blocking, debuggability / interactive term. I tried asyncrun but the debugger wouldn't work there either.

**Comment by codeinabox** [comment]
Thank you for raising this, do you envisage this as a new strategy or a modification to the Dispatch strategy?

**Comment by lisamburns** [comment]
Looks like the Dispatch strategy currently has two options or "identifiers", (dispatch and dispatch_background), I was thinking this could be the third (dispatch_spawn) ?

**Comment by codeinabox** [comment]
Sounds good to me, would like to have a try raising a PR for this new strategy? Happy to give a hand
