### ISSUE TITLE
Is `g:test#runner_commands` not documented?

### ISSUE THREAD

**Issue by kyoh86** [vim-test/vim-test#768]
I cannot find the `g:test#runner_commands` in doc/test.txt.

**Comment by codeinabox** [comment]
Hello there, what are you trying to do? There is [some documentation in the README](https://github.com/vim-test/vim-test#runner-commands). I'll try to update the documentation in doc/test.txt

**Comment by kyoh86** [comment]
To read README, it needs also web browser not only vim.
I just want it to be described in doc/test.txt.

**Comment by dkaszews** [comment]
There's a bunch of stuff that is missing from the docs, makes sense that it should be available there. Is there some existing way to generate one from the other to avoid having to write stuff in two places?

**Comment by kyoh86** [comment]
Markdown offers a variety of formatting options for appearance, while the vim-help format is more limited in this regard.
However, vim-help excels with its jump tags *...* and links |...|, which are not inherent features of Markdown
Given these significant differences in functionality and expressiveness, direct conversion between the two can be challenging.

Although some plugins claim to convert Markdown to vim-help, the results are often subpar, with poor quality and missing tags.

For documents that require images, it may be preferable to use Markdown for introductory sections and reserve the vim-help format for detailed descriptions, linking between the two as needed.
Despite being a text file, vim-help is adequately readable in web browsers and Vim.

**Comment by codeinabox** [comment]
Using tooling to keep the README and docs/test.tsx is probably overkill. I'll update the latter when I get the chance
