### ISSUE TITLE
Running into Python "Not a test file" error

### ISSUE THREAD

**Issue by sigcyc** [vim-test/vim-test#788]
It used to work, but after upgrading neovim to 0.9.5, I couldn't run vim-test. It will say "Not a test file"

**Comment by codeinabox** [comment]
Apologies, there were some changes to test runner detection, which Python runner are you expecting it to run?

**Comment by sigcyc** [comment]
I haven't set a runner before, though I expect it to run pytest

**Comment by sigcyc** [comment]
After digging into the comments in the commits, setting `let g:test#python#runner = "pytest"` solve my problem

https://github.com/vim-test/vim-test/pull/785

**Comment by codeinabox** [comment]
Out of curiosity do you have a pytest.ini or a pyproject.toml file with [tool.pytest.ini_options] in your project? I'm going to add checks for that as part of the PyTest detection

**Comment by sigcyc** [comment]
I have a pyproject.toml but no [tool.pytest.ini_options].

**Comment by codeinabox** [comment]
I've created a PR #790 to improve pytest detection, however I am not sure that it will cover your situation. Do you use any of the configuration methods listed here? https://docs.pytest.org/en/7.1.x/reference/customize.html

**Comment by codeinabox** [comment]
I've merged in the above PR. It also restores the original functionality of falling back to pytest if the executable is present, so you shouldn't have to use `let g:test#python#runner = "pytest"`
