### ISSUE TITLE
help needed to execute python file 

### ISSUE THREAD

**Issue by Trid-collab** [vim-test/vim-test#792]
Please pardon me for my maybe trivial query.I am trying to learn python. I am trying to migrate from vscode wherein I could just click a button to run the python file which I was editiing or learning from to be executable in a separate output pane below or a terminal for interactive session. 
While migrating to neovim I was searching for a similar functionality when I came across this plugin. I installed it and tried to run the xxx.py file - but then it says test file not found. I still not that advanced where I know about unit tests and test file - just basic python files to run like `!python3 %'
Would it be possible to so with this plugin using the strategies for directing the output to another tumx pane, iterm pane , wezterm pane etc. or do I need to search for all other alternaitves

**Comment by codeinabox** [comment]
Hello and thank you for the question, so you are looking for a way to execute a Python file, not necessarily a test file? If so, what you are looking for is a REPL, for which there are several plug-ins:

- [iron.nvim](https://github.com/Vigemus/iron.nvim)
- [vim-repl](https://github.com/sillybun/vim-repl)
