### ISSUE TITLE
Suppressing color output prevents Dispatch pane auto-closing

### ISSUE THREAD

**Issue by Geraint** [vim-test/vim-test#793]
#777 has introduced an issue for me.

Previously, when tests completed successfully, the pane auto-closed.

Now, it stays open.

If I change

```vim
function! test#strategy#dispatch(cmd) abort
  execute 'Dispatch NO_COLOR=1 '.a:cmd
endfunction
```

... back to

```vim
function! test#strategy#dispatch(cmd) abort
  execute 'Dispatch '.a:cmd
endfunction
```

... the problem goes away.

**Comment by codeinabox** [comment]
Thank you for letting me know. I shall look into either fixing or reverting this change

**Comment by kronn** [comment]
Great timing, I just ran into this and landed here.

Is it possible to pass the ENV-Var in another way?
Maybe this is something that belongs into vim-dispatch itself?

**Comment by codeinabox** [comment]
I've reverted this change and will look into other way to address #776
