### ISSUE TITLE
Project config file?

### ISSUE THREAD

**Issue by anhari** [vim-test/vim-test#813]
Hi, thanks for this amazing plugin! I've been using it for so many years.

I was wondering if it's possible to have a config file in a project directory to determine which JavaScript runner to use? I'm working on a project that uses both playwright and vitest, but I'd rather use the `vitest` as the default runner. Is there a way to specify for this project only to use vitest?

**Comment by GiuseppeMP** [comment]
@anhari I'm not familiar with `vitest` but I'm using autocmds to change runners in python and java..

Perhaps, it may help you. Idk if there are another ways to achieve this. Note that I put `vite.config.ts` on the example, but if you know better files to detect if it's a vitest project, you can change.

```lua
vim.api.nvim_create_autocmd("VimEnter", {
    callback = function(_event)
        vim.cmd([[
            if filereadable("vite.config.ts")
                let test#javascript#runner = 'vitest'
                let test#typescript#runner = 'vitest'
            endif
        ]])
    end
})
```

**Comment by codeinabox** [comment]
@anhari good question! What does your package.json look like, and what test configuration files do you have? Where possible, I like to make vim-test adhere to a zero configuration philosophy and instead use detection to best determine the runner to use.

**Comment by anhari** [comment]
> @anhari good question! What does your package.json look like, and what test configuration files do you have? Where possible, I like to make vim-test adhere to a zero configuration philosophy and instead use detection to best determine the runner to use.

Here's my `package.json` file

``` js
  ...
  "devDependencies": {
    "@playwright/test": "^1.46.1",
    "@prisma/client": "^5.22.0",
    "@testing-library/dom": "^10.4.0",
    "@testing-library/react": "^16.0.1",
    "@types/bcrypt": "^5.0.2",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@vitejs/plugin-react": "^4.3.1",
    "dotenv-cli": "^7.4.2",
    "eslint": "^8",
    "eslint-config-next": "14.2.7",
    "jsdom": "^25.0.0",
    "postcss": "^8",
    "prisma": "^5.22.0",
    "tailwindcss": "^3.4.1",
    "typescript": "^5",
    "vite-tsconfig-paths": "^5.1.2",
    "vitest": "^2.0.5",
    "vitest-environment-vprisma": "^1.3.0"
  },
...
```

My testing config files look something like this:

``` js
/* vitest.config.ts */
import { defineConfig } from "vitest/config";
import tsconfigPaths from "vite-tsconfig-paths";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  test: {
    environment: "jsdom",
    exclude: [
      "**/node_modules/**",
      "**/dist/**",
      "**/tests/e2e/**",
      "**/.{idea,git,cache,output,temp}/**",
      "**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*",
    ],
    setupFiles: "vitest.setup.ts",
  },
});
```

```js
/* playwright.config.ts */
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests/e2e",
  ...
});

**Comment by codeinabox** [comment]
> Hi, thanks for this amazing plugin! I've been using it for so many years.
> 
> I was wondering if it's possible to have a config file in a project directory to determine which JavaScript runner to use? I'm working on a project that uses both playwright and vitest, but I'd rather use the `vitest` as the default runner. Is there a way to specify for this project only to use vitest?

Thank you! Yes, this scenario is covered in the documentation, see https://github.com/vim-test/vim-test?tab=readme-ov-file#javascript

You can simply use `let g:test#javascript#runner = 'vitest'`

**Comment by anhari** [comment]
That works for me, thanks @codeinabox! I wrote a quick little neovim script that let's me toggle the default runner using telescope.
