### ISSUE TITLE
Vscode Neovim runner.

### ISSUE THREAD

**Issue by chaudry-786** [vim-test/vim-test#822]
Hi, 
Thanks for this amazing plugin. I use [Neovim in VS Code ](https://github.com/vscode-neovim/vscode-neovim) and wrote a simple runner for it.

Please add into the plugin.
```
if vim.g.vscode then
    -- Custom vim-test Strategy for VS Code Terminal
    -- Runs test commands in the VS Code terminal when using Neovim in VS Code.
    -- Focuses the terminal, clears it, and sends the test command.
    vim.cmd([[
        function! VSCodeStrategy(cmd)
            " Optional: Focus the VS Code terminal
            " call VSCodeNotify('workbench.action.terminal.focus')
            " Clear the terminal
            call VSCodeNotify('workbench.action.terminal.sendSequence', {'text': "clear\n"})
            " Send the test command to the terminal
            call VSCodeNotify('workbench.action.terminal.sendSequence', {'text': a:cmd . "\n"})
        endfunction

    let g:test#custom_strategies = {'vscode': function('VSCodeStrategy')}
    let g:test#strategy = 'vscode'
    ]])
else
    vim.g["test#strategy"] = "vimux"
end

```

**Comment by dkaszews** [comment]
Hi! Thank you for contributing, you can use https://github.com/vim-test/vim-test/pull/766 as a guide for adding a new strategy to the repository. You are most of the way there, just make sure you adhere to code organization and style. 

I suggest taking a look at it and https://github.com/vim-test/vim-test/pull/770 to see which options can be reimplemented in your strategy. I would suggest naming it `neovim_vscode` for consistency.
