### ISSUE TITLE
Setting `test#strategy` has no effect

### ISSUE THREAD

**Issue by schnittchen** [vim-test/vim-test#826]
I've tried

```
:let g:test#strategy = "neovim_vscode"
:let g:test#strategy = "foo"
:let test#strategy = "neovim_vscode"
:let test#strategy = "foo"
```

and nothing ever changes. I've read out the value using `let [g:]test#strategy` after test running to make sure it's not overwritten.

**Comment by dkaszews** [comment]
What command are you using to execute your commands? I have found that some, especially `TestLatest`, reuse the last settings.

Looking at source: https://github.com/vim-test/vim-test/blob/8872ec0f788af934386b2aef0cd28a5c2b923146/autoload/test.vim#L70-L77 there are some flows where the setting is not read. You can try print-debugging that file by adding some `echom strategy` and sourcing it or restarting vim to update plugin source code.

**Comment by schnittchen** [comment]
I don't remember exactly, but the problem had a sane explanation in the end (plugin manager or similar)
